[package]
name = "ghaction_version_gen"
description = "Generate various version options as github action outputs"
version = "0.8.0"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
structopt = { version = "0", features = [ "paw" ] }
paw = "1"
regex = "1"
anyhow = "1"
toml = "0.5"

[dev-dependencies]
tempfile = "3"
serial_test = "0.5"
