[package]
name = "ghaction_version_gen"
description = "Generate various version options as github action outputs"
version = "0.9.0"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
structopt = { version = "0.3.26", features = [ "paw" ] }
paw = "1.0.0"
regex = "1.5.6"
anyhow = "1.0.57"
toml = "0.5.9"

[dev-dependencies]
tempfile = "3.3.0"
