[package]
name = "githeadinfo"
description = "Show pieces of information about HEAD in github action output format"
version = "0.0.1"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
structopt = { version = "0", features = [ "paw" ] }
paw = "1"
regex = "1"
anyhow = "1"

[dev-dependencies]
tempfile = "3"
