[package]
name = "ghaction_version_gen"
description = "Generate various version options as github action outputs"
version = "0.10.0"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
edition = "2021"
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["github-action", "version-generate"]

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
regex = "1.6.0"
anyhow = "1.0.62"
toml = "0.5.9"

[dev-dependencies]
tempfile = "3.3.0"
