---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    uses: lpenz/omnilint/.github/workflows/omnilint.yml@v0.5
  rust:
    uses: lpenz/ghworkflow-rust/.github/workflows/rust.yml@v0.11.0
    with:
      dependencies_debian: git
      coveralls: true
      publish_cratesio: true
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/build-push-action@v3.2.0
        with:
          push: false
  publish-dockerhub:
    needs: [ omnilint, rust, docker-build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - id: version
        uses: ./
      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ steps.version.outputs.version_docker_ci != 'null' }}
      - uses: docker/build-push-action@v3.2.0
        with:
          push: ${{ steps.version.outputs.version_docker_ci != 'null' }}
          tags: ${{ github.repository }}:${{ steps.version.outputs.version_docker_ci }}
