---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    uses: lpenz/omnilint/.github/workflows/omnilint.yml@v0.5
  rust:
    uses: lpenz/ghworkflow-rust/.github/workflows/rust.yml@v0.9.0
    with:
      dependencies_debian: git
      coveralls: true
      publish_cratesio: true
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: docker/build-push-action@v3.1.1
        with:
          push: false
  publish-dockerhub:
    needs: [ omnilint, rust, docker-build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - id: version
        uses: ./
      - uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ steps.version.outputs.version_docker_ci != 'null' }}
      - uses: docker/build-push-action@v3.1.1
        with:
          push: ${{ steps.version.outputs.version_docker_ci != 'null' }}
          tags: ${{ github.repository }}:${{ steps.version.outputs.version_docker_ci }}
  publish-github-release:
    needs: [ publish-dockerhub ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.10.0
      - name: publish github release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        if: steps.version.outputs.version_tagged != ''
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
